### ISSUE TITLE
Configuration "doNotReplaceURL: true" not working

### ISSUE THREAD

**Issue by ITernovtsii** [scaleflex/vue-cloudimage-responsive-plain#1]
STR:
- open https://codesandbox.io/s/vue-cloudimage-responsive-example-bqg7g?file=/src/App.vue
- add `doNotReplaceURL: true` to config
- change image src to `https://jolipage.airstore.io/img.jpg`

Actual result:
Image loaded from "https://demo.cloudimg.io/v7/https://jolipage.airstore.io/img.jpg?w=84&ci_info="

Expected result:
Image loaded from "https://jolipage.airstore.io/img.jpg?w=84&ci_info="

**Comment by amrelbialy** [comment]
hey @ITernovtsiy  ,
Thanks for telling us ! , Yes it wasn't working .
we will fix it and release the new version
