### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by luger95** [scaleflex/vue-cloudimage-responsive-plain#3]
`import Img, { CloudImageProvider } from 'vue-cloudimage-responsive-plain';`

`<template>
  <cloud-image-provider :cloud-image-config="cloudimageConfig">
    <h1>Simple demo of vue-cloudimage-responsive</h1>
    <Img src="img.jpg" alt="Demo image" />
  </cloud-image-provider>
</template>`

`<script>
export default{
  components: {
    CloudimageProvider,
    Img
  },
  data() {
    return {
      cloudimageConfig: {
	    token: 'aldkilvkeo',
		baseURL: 'https://jolipage.airstore.io/',
	  },
    }
  },
}
</script>`

**Comment by amrelbialy** [comment]
Hi @luger95  , can you please explain more why we need to update documentation

**Comment by luger95** [comment]
While using the examples in the documentation, I encountered some naming and placement errors.

Adjusting the documentation will make it easier for future users to use your library.

**Comment by amrelbialy** [comment]
Vue uses kebab-case and PascalCase . If you intialize it in PascalCase you can also reference it in kebab-case
