### ISSUE TITLE
How to defined alt value ?

### ISSUE THREAD

**Issue by luger95** [scaleflex/vue-cloudimage-responsive-plain#4]
Hello

I can't define the values of the class and alt attributes of <img. 
Is it possible not to create the first div ?

### Code 
`<cloud-image-provider :cloud-image-config="cloudimageConfig">
    <Img :src="product['image-url']" class="card-img" :alt="product.name" />
</cloud-image-provider>`

### Result
[![result.png](https://i.postimg.cc/W1Q5HSmt/result.png)](https://postimg.cc/5XS5HBRM)

**Comment by amrelbialy** [comment]
Thank you for informing us , now it is not possible but we will make it available to add it to img tag in the next release

**Comment by luger95** [comment]
Ok, thanks. When is the next release ?

**Comment by amrelbialy** [comment]
New version is released
