### ISSUE TITLE
Add an $emit on image loading

### ISSUE THREAD

**Issue by luger95** [scaleflex/vue-cloudimage-responsive-plain#5]
Hello,

Is it possible to add an $emit on the loading status of an image?

I would like to capture the moment when the image is fully loaded . I found that there was a css class "loaded".

Thank you.

**Comment by amrelbialy** [comment]
Hey @luger95 ,

Now isn't possible to capture status of image on load , we will add it in next release.

**Comment by amrelbialy** [comment]
[https://github.com/scaleflex/vue-cloudimage-responsive-plain#onimgload](url)
