### ISSUE TITLE
How to defined width and height value

### ISSUE THREAD

**Issue by NicolasLoisirsEncheres** [scaleflex/vue-cloudimage-responsive-plain#6]
Hi, 

I'm trying to set width and height properties on <Img/> component like this :
`<Img
                :alt="data.alt"
                :class="data.class"
                :src="data.src"
                width="255"
                height="156"
            />`

In the result I only have the alt/class/src properties in the code : 
`<img src="" alt="" class="" >`

How can I have this 
`<img src="" alt="" class="" width="255" height="156">`

Thanks

**Comment by amrelbialy** [comment]
Hey @NicolasLoisirsEncheres , please check documentation 
For width: https://github.com/scaleflex/vue-cloudimage-responsive-plain#width
For Height: https://github.com/scaleflex/vue-cloudimage-responsive-plain#height

**Comment by NicolasLoisirsEncheres** [comment]
```
<cloud-image-provider :cloud-image-config="config">
    <client-only>
            <Img
                :alt="data.alt"
                :class="data.class"
                :itemprop="data.itemprop"
                :src="data.src ? data.src : data.url"
                :width="data.width"
                :height="data.height"
            />
    </client-only>
</cloud-image-provider>
```

It return a html element like this `<img alt="" class="" itemprop="" src="">` without width="" and height="" attributes maybe width and height cannot be dynamic ?
Note: width and height values in data prop are strings

**Comment by amrelbialy** [comment]
@NicolasLoisirsEncheres  width and height can be dynamic , but when adding width and height props we don't show it in element styles or as an attrubute, so to check if width and height is working you can add to config  (params: 'ci_info=1&org_if_sml=1'). It adds text on the image and shows the resolution of the image like in demo . Also if you checked the src of the image you will see that we add width and height queries like that (w=450&h=450)

**Comment by NicolasLoisirsEncheres** [comment]
I saw the w and h in the query, but my question is "is it possible to have width and height in html attribute ?"
Because a best pratice to reduce cumulative layout shift is to have width and height html attributes in img tag
cf : https://web.dev/optimize-cls/

**Comment by amrelbialy** [comment]
Hey @NicolasLoisirsEncheres, now it isn't possible , also checked the cumulative layout shift and yes we have some issues with it, will fix in next release. Thanks for pointing out this issue.
